// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runespace/v1/errors.proto

package runespacepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorReason is the machine-readable cause attached to a failed RPC via a
// google.rpc.ErrorInfo status detail; the gRPC status code stays the coarse
// classifier. Clients branch on the code first, then on the reason for precise
// handling (mapping lives in internal/server/grpcerr.go).
type ErrorReason int32

const (
	ErrorReason_ERROR_REASON_UNSPECIFIED ErrorReason = 0
	// INVALID_ARGUMENT — caller input.
	ErrorReason_ERROR_REASON_INVALID_ID                ErrorReason = 1
	ErrorReason_ERROR_REASON_MISSING_RMP_ITEM          ErrorReason = 2
	ErrorReason_ERROR_REASON_MISSING_MM_ITEM           ErrorReason = 13 // mm_item is required on every insert
	ErrorReason_ERROR_REASON_INVALID_METADATA_JSON     ErrorReason = 3
	ErrorReason_ERROR_REASON_MISSING_QUERY             ErrorReason = 4
	ErrorReason_ERROR_REASON_MISSING_ID                ErrorReason = 5
	ErrorReason_ERROR_REASON_MISSING_EVAL_KEYS         ErrorReason = 6
	ErrorReason_ERROR_REASON_EVAL_KEY_INTEGRITY        ErrorReason = 7  // a streamed eval key failed its length/sha256 check
	ErrorReason_ERROR_REASON_INVALID_CLUSTER_ID        ErrorReason = 8  // cluster_id outside [0, nlist) on a cluster insert
	ErrorReason_ERROR_REASON_CENTROID_VERSION_MISMATCH ErrorReason = 9  // insert's centroid_set_version != the loaded set
	ErrorReason_ERROR_REASON_INVALID_TAG               ErrorReason = 14 // a required filter-tag arg is empty, or RetagAll from == to
	// FAILED_PRECONDITION — server state.
	ErrorReason_ERROR_REASON_KEYS_NOT_REGISTERED      ErrorReason = 10
	ErrorReason_ERROR_REASON_KEY_ROTATION_UNSUPPORTED ErrorReason = 11
	ErrorReason_ERROR_REASON_CLUSTER_NOT_CONFIGURED   ErrorReason = 12 // mm_item sent but the instance has no centroid set
	// UNAVAILABLE — transient, retryable.
	ErrorReason_ERROR_REASON_MANIFEST_BUSY ErrorReason = 20
	// RESOURCE_EXHAUSTED — a hard capacity limit was hit.
	ErrorReason_ERROR_REASON_MAX_ROWS_EXCEEDED ErrorReason = 50 // insert rejected: engine.max_rows cap reached
	// INTERNAL — opaque to the client; the cause is server-side logs only.
	ErrorReason_ERROR_REASON_ENGINE_FAILURE ErrorReason = 30
	ErrorReason_ERROR_REASON_MANIFEST_IO    ErrorReason = 31
	ErrorReason_ERROR_REASON_WAL_IO         ErrorReason = 32
	// CANCELED / DEADLINE_EXCEEDED — the caller went away mid-request.
	ErrorReason_ERROR_REASON_REQUEST_CANCELED ErrorReason = 40
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "ERROR_REASON_UNSPECIFIED",
		1:  "ERROR_REASON_INVALID_ID",
		2:  "ERROR_REASON_MISSING_RMP_ITEM",
		13: "ERROR_REASON_MISSING_MM_ITEM",
		3:  "ERROR_REASON_INVALID_METADATA_JSON",
		4:  "ERROR_REASON_MISSING_QUERY",
		5:  "ERROR_REASON_MISSING_ID",
		6:  "ERROR_REASON_MISSING_EVAL_KEYS",
		7:  "ERROR_REASON_EVAL_KEY_INTEGRITY",
		8:  "ERROR_REASON_INVALID_CLUSTER_ID",
		9:  "ERROR_REASON_CENTROID_VERSION_MISMATCH",
		14: "ERROR_REASON_INVALID_TAG",
		10: "ERROR_REASON_KEYS_NOT_REGISTERED",
		11: "ERROR_REASON_KEY_ROTATION_UNSUPPORTED",
		12: "ERROR_REASON_CLUSTER_NOT_CONFIGURED",
		20: "ERROR_REASON_MANIFEST_BUSY",
		50: "ERROR_REASON_MAX_ROWS_EXCEEDED",
		30: "ERROR_REASON_ENGINE_FAILURE",
		31: "ERROR_REASON_MANIFEST_IO",
		32: "ERROR_REASON_WAL_IO",
		40: "ERROR_REASON_REQUEST_CANCELED",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED":               0,
		"ERROR_REASON_INVALID_ID":                1,
		"ERROR_REASON_MISSING_RMP_ITEM":          2,
		"ERROR_REASON_MISSING_MM_ITEM":           13,
		"ERROR_REASON_INVALID_METADATA_JSON":     3,
		"ERROR_REASON_MISSING_QUERY":             4,
		"ERROR_REASON_MISSING_ID":                5,
		"ERROR_REASON_MISSING_EVAL_KEYS":         6,
		"ERROR_REASON_EVAL_KEY_INTEGRITY":        7,
		"ERROR_REASON_INVALID_CLUSTER_ID":        8,
		"ERROR_REASON_CENTROID_VERSION_MISMATCH": 9,
		"ERROR_REASON_INVALID_TAG":               14,
		"ERROR_REASON_KEYS_NOT_REGISTERED":       10,
		"ERROR_REASON_KEY_ROTATION_UNSUPPORTED":  11,
		"ERROR_REASON_CLUSTER_NOT_CONFIGURED":    12,
		"ERROR_REASON_MANIFEST_BUSY":             20,
		"ERROR_REASON_MAX_ROWS_EXCEEDED":         50,
		"ERROR_REASON_ENGINE_FAILURE":            30,
		"ERROR_REASON_MANIFEST_IO":               31,
		"ERROR_REASON_WAL_IO":                    32,
		"ERROR_REASON_REQUEST_CANCELED":          40,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_runespace_v1_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_runespace_v1_errors_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_runespace_v1_errors_proto_rawDescGZIP(), []int{0}
}

var File_runespace_v1_errors_proto protoreflect.FileDescriptor

const file_runespace_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x19runespace/v1/errors.proto\x12\frunespace.v1*\xe3\x05\n" +
	"\vErrorReason\x12\x1c\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ERROR_REASON_INVALID_ID\x10\x01\x12!\n" +
	"\x1dERROR_REASON_MISSING_RMP_ITEM\x10\x02\x12 \n" +
	"\x1cERROR_REASON_MISSING_MM_ITEM\x10\r\x12&\n" +
	"\"ERROR_REASON_INVALID_METADATA_JSON\x10\x03\x12\x1e\n" +
	"\x1aERROR_REASON_MISSING_QUERY\x10\x04\x12\x1b\n" +
	"\x17ERROR_REASON_MISSING_ID\x10\x05\x12\"\n" +
	"\x1eERROR_REASON_MISSING_EVAL_KEYS\x10\x06\x12#\n" +
	"\x1fERROR_REASON_EVAL_KEY_INTEGRITY\x10\a\x12#\n" +
	"\x1fERROR_REASON_INVALID_CLUSTER_ID\x10\b\x12*\n" +
	"&ERROR_REASON_CENTROID_VERSION_MISMATCH\x10\t\x12\x1c\n" +
	"\x18ERROR_REASON_INVALID_TAG\x10\x0e\x12$\n" +
	" ERROR_REASON_KEYS_NOT_REGISTERED\x10\n" +
	"\x12)\n" +
	"%ERROR_REASON_KEY_ROTATION_UNSUPPORTED\x10\v\x12'\n" +
	"#ERROR_REASON_CLUSTER_NOT_CONFIGURED\x10\f\x12\x1e\n" +
	"\x1aERROR_REASON_MANIFEST_BUSY\x10\x14\x12\"\n" +
	"\x1eERROR_REASON_MAX_ROWS_EXCEEDED\x102\x12\x1f\n" +
	"\x1bERROR_REASON_ENGINE_FAILURE\x10\x1e\x12\x1c\n" +
	"\x18ERROR_REASON_MANIFEST_IO\x10\x1f\x12\x17\n" +
	"\x13ERROR_REASON_WAL_IO\x10 \x12!\n" +
	"\x1dERROR_REASON_REQUEST_CANCELED\x10(B?Z=github.com/CryptoLabInc/runespace/pkg/runespacepb;runespacepbb\x06proto3"

var (
	file_runespace_v1_errors_proto_rawDescOnce sync.Once
	file_runespace_v1_errors_proto_rawDescData []byte
)

func file_runespace_v1_errors_proto_rawDescGZIP() []byte {
	file_runespace_v1_errors_proto_rawDescOnce.Do(func() {
		file_runespace_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runespace_v1_errors_proto_rawDesc), len(file_runespace_v1_errors_proto_rawDesc)))
	})
	return file_runespace_v1_errors_proto_rawDescData
}

var file_runespace_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_runespace_v1_errors_proto_goTypes = []any{
	(ErrorReason)(0), // 0: runespace.v1.ErrorReason
}
var file_runespace_v1_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runespace_v1_errors_proto_init() }
func file_runespace_v1_errors_proto_init() {
	if File_runespace_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runespace_v1_errors_proto_rawDesc), len(file_runespace_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_runespace_v1_errors_proto_goTypes,
		DependencyIndexes: file_runespace_v1_errors_proto_depIdxs,
		EnumInfos:         file_runespace_v1_errors_proto_enumTypes,
	}.Build()
	File_runespace_v1_errors_proto = out.File
	file_runespace_v1_errors_proto_goTypes = nil
	file_runespace_v1_errors_proto_depIdxs = nil
}
