// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runespace/v1/runespace.proto

package runespacepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KeyKind identifies which eval key a RegisterKeysStream sequence carries.
type KeyKind int32

const (
	KeyKind_KEY_KIND_UNSPECIFIED KeyKind = 0
	KeyKind_KEY_KIND_RMP_EVAL    KeyKind = 1 // PUBLIC RMP eval key (IP0)
	KeyKind_KEY_KIND_MM_EVAL     KeyKind = 2 // PUBLIC MM eval key (IP1+)
)

// Enum value maps for KeyKind.
var (
	KeyKind_name = map[int32]string{
		0: "KEY_KIND_UNSPECIFIED",
		1: "KEY_KIND_RMP_EVAL",
		2: "KEY_KIND_MM_EVAL",
	}
	KeyKind_value = map[string]int32{
		"KEY_KIND_UNSPECIFIED": 0,
		"KEY_KIND_RMP_EVAL":    1,
		"KEY_KIND_MM_EVAL":     2,
	}
)

func (x KeyKind) Enum() *KeyKind {
	p := new(KeyKind)
	*p = x
	return p
}

func (x KeyKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyKind) Descriptor() protoreflect.EnumDescriptor {
	return file_runespace_v1_runespace_proto_enumTypes[0].Descriptor()
}

func (KeyKind) Type() protoreflect.EnumType {
	return &file_runespace_v1_runespace_proto_enumTypes[0]
}

func (x KeyKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyKind.Descriptor instead.
func (KeyKind) EnumDescriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{0}
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Build metadata (injected via -ldflags at build time).
	Version   string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit    string `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	BuildDate string `protobuf:"bytes,3,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	// Live engine self-check via cgo.
	EngineStatus   string `protobuf:"bytes,4,opt,name=engine_status,json=engineStatus,proto3" json:"engine_status,omitempty"`          // "ok" or an error string
	EngineProbeDim uint32 `protobuf:"varint,5,opt,name=engine_probe_dim,json=engineProbeDim,proto3" json:"engine_probe_dim,omitempty"` // dim reported by a throwaway evi context
	// True once eval keys have been registered (data plane is open).
	Ready bool `protobuf:"varint,6,opt,name=ready,proto3" json:"ready,omitempty"`
	// Identity + fingerprint of each registered eval key, persisted at
	// registration. A client compares these against its local key set to confirm
	// the instance is serving its keys (see RegisterKeysStream / KeyMeta).
	RegisteredKeys []*KeyMeta `protobuf:"bytes,7,rep,name=registered_keys,json=registeredKeys,proto3" json:"registered_keys,omitempty"`
	// Space occupancy (counts only; no byte/disk accounting).
	Stats         *SpaceStats `protobuf:"bytes,8,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetInfoResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *GetInfoResponse) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *GetInfoResponse) GetEngineStatus() string {
	if x != nil {
		return x.EngineStatus
	}
	return ""
}

func (x *GetInfoResponse) GetEngineProbeDim() uint32 {
	if x != nil {
		return x.EngineProbeDim
	}
	return 0
}

func (x *GetInfoResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *GetInfoResponse) GetRegisteredKeys() []*KeyMeta {
	if x != nil {
		return x.RegisteredKeys
	}
	return nil
}

func (x *GetInfoResponse) GetStats() *SpaceStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// SpaceStats is a point-in-time count of the instance's occupancy. Counts only:
// no on-disk byte accounting (that would need a directory walk). rows and
// tombstoned are read from the manifest's in-memory counters (O(1)).
type SpaceStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint64                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`                      // live (non-tombstoned) items currently indexed
	MaxRows       uint64                 `protobuf:"varint,2,opt,name=max_rows,json=maxRows,proto3" json:"max_rows,omitempty"` // configured hard cap enforced at insert; 0 = unlimited
	Tombstoned    uint64                 `protobuf:"varint,3,opt,name=tombstoned,proto3" json:"tombstoned,omitempty"`          // soft-deleted items awaiting physical reclaim
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceStats) Reset() {
	*x = SpaceStats{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceStats) ProtoMessage() {}

func (x *SpaceStats) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceStats.ProtoReflect.Descriptor instead.
func (*SpaceStats) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{2}
}

func (x *SpaceStats) GetRows() uint64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *SpaceStats) GetMaxRows() uint64 {
	if x != nil {
		return x.MaxRows
	}
	return 0
}

func (x *SpaceStats) GetTombstoned() uint64 {
	if x != nil {
		return x.Tombstoned
	}
	return 0
}

type RegisterKeysStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterKeysStreamResponse) Reset() {
	*x = RegisterKeysStreamResponse{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterKeysStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterKeysStreamResponse) ProtoMessage() {}

func (x *RegisterKeysStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterKeysStreamResponse.ProtoReflect.Descriptor instead.
func (*RegisterKeysStreamResponse) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{3}
}

// RegisterKeysStreamRequest is one frame of a RegisterKeysStream. Each key is
// sent as exactly one header, its data chunks in order, then one footer. Send
// all of one key's frames before starting the next.
type RegisterKeysStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RegisterKeysStreamRequest_Header
	//	*RegisterKeysStreamRequest_Data
	//	*RegisterKeysStreamRequest_Footer
	Payload       isRegisterKeysStreamRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterKeysStreamRequest) Reset() {
	*x = RegisterKeysStreamRequest{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterKeysStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterKeysStreamRequest) ProtoMessage() {}

func (x *RegisterKeysStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterKeysStreamRequest.ProtoReflect.Descriptor instead.
func (*RegisterKeysStreamRequest) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterKeysStreamRequest) GetPayload() isRegisterKeysStreamRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RegisterKeysStreamRequest) GetHeader() *KeyHeader {
	if x != nil {
		if x, ok := x.Payload.(*RegisterKeysStreamRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *RegisterKeysStreamRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*RegisterKeysStreamRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *RegisterKeysStreamRequest) GetFooter() *KeyFooter {
	if x != nil {
		if x, ok := x.Payload.(*RegisterKeysStreamRequest_Footer); ok {
			return x.Footer
		}
	}
	return nil
}

type isRegisterKeysStreamRequest_Payload interface {
	isRegisterKeysStreamRequest_Payload()
}

type RegisterKeysStreamRequest_Header struct {
	Header *KeyHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type RegisterKeysStreamRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // a contiguous slice of the current key's bytes
}

type RegisterKeysStreamRequest_Footer struct {
	Footer *KeyFooter `protobuf:"bytes,3,opt,name=footer,proto3,oneof"`
}

func (*RegisterKeysStreamRequest_Header) isRegisterKeysStreamRequest_Payload() {}

func (*RegisterKeysStreamRequest_Data) isRegisterKeysStreamRequest_Payload() {}

func (*RegisterKeysStreamRequest_Footer) isRegisterKeysStreamRequest_Payload() {}

type KeyHeader struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Kind     KeyKind                `protobuf:"varint,1,opt,name=kind,proto3,enum=runespace.v1.KeyKind" json:"kind,omitempty"`
	TotalLen uint64                 `protobuf:"varint,2,opt,name=total_len,json=totalLen,proto3" json:"total_len,omitempty"` // full key length; the server fast-fails on mismatch
	// Key identity carried with the stream. The server pairs these with the
	// footer's sha256 to persist a KeyMeta for cross-verification.
	Kid           string `protobuf:"bytes,3,opt,name=kid,proto3" json:"kid,omitempty"`                           // key identifier
	Preset        string `protobuf:"bytes,4,opt,name=preset,proto3" json:"preset,omitempty"`                     // CKKS preset, e.g. "IP0"
	Dim           uint32 `protobuf:"varint,5,opt,name=dim,proto3" json:"dim,omitempty"`                          // embedding dimension
	EvalMode      string `protobuf:"bytes,6,opt,name=eval_mode,json=evalMode,proto3" json:"eval_mode,omitempty"` // evi eval mode, e.g. "rmp"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyHeader) Reset() {
	*x = KeyHeader{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyHeader) ProtoMessage() {}

func (x *KeyHeader) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyHeader.ProtoReflect.Descriptor instead.
func (*KeyHeader) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{5}
}

func (x *KeyHeader) GetKind() KeyKind {
	if x != nil {
		return x.Kind
	}
	return KeyKind_KEY_KIND_UNSPECIFIED
}

func (x *KeyHeader) GetTotalLen() uint64 {
	if x != nil {
		return x.TotalLen
	}
	return 0
}

func (x *KeyHeader) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *KeyHeader) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *KeyHeader) GetDim() uint32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *KeyHeader) GetEvalMode() string {
	if x != nil {
		return x.EvalMode
	}
	return ""
}

type KeyFooter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        []byte                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"` // digest over all of this key's data bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyFooter) Reset() {
	*x = KeyFooter{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyFooter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyFooter) ProtoMessage() {}

func (x *KeyFooter) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyFooter.ProtoReflect.Descriptor instead.
func (*KeyFooter) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{6}
}

func (x *KeyFooter) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

// KeyMeta is the identity and fingerprint of one registered eval key. The
// client derives it from the key set; the server persists it next to the raw
// key bytes and echoes it from GetInfo, so both sides hold the same record.
type KeyMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          KeyKind                `protobuf:"varint,1,opt,name=kind,proto3,enum=runespace.v1.KeyKind" json:"kind,omitempty"`
	Kid           string                 `protobuf:"bytes,2,opt,name=kid,proto3" json:"kid,omitempty"`
	Preset        string                 `protobuf:"bytes,3,opt,name=preset,proto3" json:"preset,omitempty"`
	Dim           uint32                 `protobuf:"varint,4,opt,name=dim,proto3" json:"dim,omitempty"`
	EvalMode      string                 `protobuf:"bytes,5,opt,name=eval_mode,json=evalMode,proto3" json:"eval_mode,omitempty"`
	Fingerprint   []byte                 `protobuf:"bytes,6,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"` // sha256 over the raw eval key bytes (== KeyFooter.sha256)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyMeta) Reset() {
	*x = KeyMeta{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyMeta) ProtoMessage() {}

func (x *KeyMeta) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyMeta.ProtoReflect.Descriptor instead.
func (*KeyMeta) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{7}
}

func (x *KeyMeta) GetKind() KeyKind {
	if x != nil {
		return x.Kind
	}
	return KeyKind_KEY_KIND_UNSPECIFIED
}

func (x *KeyMeta) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *KeyMeta) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *KeyMeta) GetDim() uint32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *KeyMeta) GetEvalMode() string {
	if x != nil {
		return x.EvalMode
	}
	return ""
}

func (x *KeyMeta) GetFingerprint() []byte {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

type InsertRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client-supplied opaque UUID. The client owns it so an ack-loss retry reuses
	// the same id and stays idempotent (existing id ⇒ no-op).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Caller-supplied metadata as a JSON document, stored verbatim in the
	// manifest. Optional; if present it must be valid JSON. Plaintext — keep
	// meaningful/secret values in the encrypted payload, not here.
	Metadata string `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Flat (RMP) representation. Required.
	RmpItem *RMPItem `protobuf:"bytes,3,opt,name=rmp_item,json=rmpItem,proto3" json:"rmp_item,omitempty"`
	// Cluster (MM) tier dual-representation. Required: every item carries both an
	// rmp_item and an mm_item, routed against the instance's centroid set.
	MmItem *MMItem `protobuf:"bytes,4,opt,name=mm_item,json=mmItem,proto3" json:"mm_item,omitempty"`
	// Opaque filter-tag set: visibility labels the engine never interprets. Empty =
	// public (survives every scope). Assigned by a trusted caller (Console) and stored
	// verbatim; Search excludes an item whose tags don't intersect the request scope
	// (see SearchRequest.filter_scope).
	FilterTags    []string `protobuf:"bytes,5,rep,name=filter_tags,json=filterTags,proto3" json:"filter_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{8}
}

func (x *InsertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *InsertRequest) GetRmpItem() *RMPItem {
	if x != nil {
		return x.RmpItem
	}
	return nil
}

func (x *InsertRequest) GetMmItem() *MMItem {
	if x != nil {
		return x.MmItem
	}
	return nil
}

func (x *InsertRequest) GetFilterTags() []string {
	if x != nil {
		return x.FilterTags
	}
	return nil
}

// RMPItem is the flat representation of an item.
type RMPItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          []byte                 `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"` // ITEM-encoded evi query (CKKS/FHE embedding)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RMPItem) Reset() {
	*x = RMPItem{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RMPItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RMPItem) ProtoMessage() {}

func (x *RMPItem) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RMPItem.ProtoReflect.Descriptor instead.
func (*RMPItem) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{9}
}

func (x *RMPItem) GetItem() []byte {
	if x != nil {
		return x.Item
	}
	return nil
}

// MMItem is the compact cluster (MM) representation of an item plus the
// plaintext routing the server stores for IVF. The client compact-encrypts
// item with encryptRow, computes cluster_id as the nearest centroid in
// plaintext, and echoes the centroid set version it routed against so the
// server can reject a stale set.
type MMItem struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Item               []byte                 `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`                                                         // compact ITEM-encoded MM row (encryptRow)
	ClusterId          uint32                 `protobuf:"varint,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`                             // hard single assignment, 0..nlist-1
	CentroidSetVersion string                 `protobuf:"bytes,3,opt,name=centroid_set_version,json=centroidSetVersion,proto3" json:"centroid_set_version,omitempty"` // must match the instance's loaded set
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MMItem) Reset() {
	*x = MMItem{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MMItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MMItem) ProtoMessage() {}

func (x *MMItem) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MMItem.ProtoReflect.Descriptor instead.
func (*MMItem) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{10}
}

func (x *MMItem) GetItem() []byte {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *MMItem) GetClusterId() uint32 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *MMItem) GetCentroidSetVersion() string {
	if x != nil {
		return x.CentroidSetVersion
	}
	return ""
}

// InsertResponse is intentionally empty: the id is client-supplied and the slot is
// internal; the ack signals a durable insert (or an idempotent no-op).
type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{11}
}

type GetCentroidsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCentroidsRequest) Reset() {
	*x = GetCentroidsRequest{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCentroidsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCentroidsRequest) ProtoMessage() {}

func (x *GetCentroidsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCentroidsRequest.ProtoReflect.Descriptor instead.
func (*GetCentroidsRequest) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{12}
}

// Centroid is one cluster's representative vector and its cluster id.
type Centroid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`           // cluster id, 0..nlist-1 (== index in the streamed set)
	Vec           []float32              `protobuf:"fixed32,2,rep,packed,name=vec,proto3" json:"vec,omitempty"` // length == dim
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Centroid) Reset() {
	*x = Centroid{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Centroid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Centroid) ProtoMessage() {}

func (x *Centroid) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Centroid.ProtoReflect.Descriptor instead.
func (*Centroid) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{13}
}

func (x *Centroid) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Centroid) GetVec() []float32 {
	if x != nil {
		return x.Vec
	}
	return nil
}

// GetCentroidsChunk is one frame of the GetCentroids server stream: exactly one
// header first, then zero or more batches carrying the centroids in id order.
type GetCentroidsChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GetCentroidsChunk_Header
	//	*GetCentroidsChunk_Batch
	Payload       isGetCentroidsChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCentroidsChunk) Reset() {
	*x = GetCentroidsChunk{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCentroidsChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCentroidsChunk) ProtoMessage() {}

func (x *GetCentroidsChunk) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCentroidsChunk.ProtoReflect.Descriptor instead.
func (*GetCentroidsChunk) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{14}
}

func (x *GetCentroidsChunk) GetPayload() isGetCentroidsChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GetCentroidsChunk) GetHeader() *CentroidSetHeader {
	if x != nil {
		if x, ok := x.Payload.(*GetCentroidsChunk_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *GetCentroidsChunk) GetBatch() *CentroidBatch {
	if x != nil {
		if x, ok := x.Payload.(*GetCentroidsChunk_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

type isGetCentroidsChunk_Payload interface {
	isGetCentroidsChunk_Payload()
}

type GetCentroidsChunk_Header struct {
	Header *CentroidSetHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type GetCentroidsChunk_Batch struct {
	Batch *CentroidBatch `protobuf:"bytes,2,opt,name=batch,proto3,oneof"`
}

func (*GetCentroidsChunk_Header) isGetCentroidsChunk_Payload() {}

func (*GetCentroidsChunk_Batch) isGetCentroidsChunk_Payload() {}

// CentroidSetHeader is the first stream frame: the set's identity and size. An
// empty version means the cluster tier is not configured on this instance (no
// batches follow), which cannot accept inserts.
type CentroidSetHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content-hash version of the set ("sha256:..."). Empty ⇒ the cluster tier is
	// not configured. Clients echo this as InsertRequest.centroid_set_version.
	Version       string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Dim           uint32 `protobuf:"varint,2,opt,name=dim,proto3" json:"dim,omitempty"`      // embedding dimension of each centroid vector
	Preset        string `protobuf:"bytes,3,opt,name=preset,proto3" json:"preset,omitempty"` // evi preset the set was trained for (e.g. "IP1")
	Nlist         uint32 `protobuf:"varint,4,opt,name=nlist,proto3" json:"nlist,omitempty"`  // total centroid count, so the client preallocates
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CentroidSetHeader) Reset() {
	*x = CentroidSetHeader{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CentroidSetHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CentroidSetHeader) ProtoMessage() {}

func (x *CentroidSetHeader) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CentroidSetHeader.ProtoReflect.Descriptor instead.
func (*CentroidSetHeader) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{15}
}

func (x *CentroidSetHeader) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CentroidSetHeader) GetDim() uint32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *CentroidSetHeader) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *CentroidSetHeader) GetNlist() uint32 {
	if x != nil {
		return x.Nlist
	}
	return 0
}

// CentroidBatch carries a contiguous, id-ordered slice of the set. The set is
// split into batches so a large set (nlist*dim floats) transfers without a
// single oversized message.
type CentroidBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Centroids     []*Centroid            `protobuf:"bytes,1,rep,name=centroids,proto3" json:"centroids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CentroidBatch) Reset() {
	*x = CentroidBatch{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CentroidBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CentroidBatch) ProtoMessage() {}

func (x *CentroidBatch) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CentroidBatch.ProtoReflect.Descriptor instead.
func (*CentroidBatch) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{16}
}

func (x *CentroidBatch) GetCentroids() []*Centroid {
	if x != nil {
		return x.Centroids
	}
	return nil
}

type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plaintext, L2-normalized query embedding. Under PCMM the query is plaintext to
	// the server regardless, so the client sends the raw (unit-normalized) vector and
	// the server QUERY-encodes it per tier (flat = RMP/IP0, cluster = MM/IP1) — the
	// two tiers use different CKKS contexts, so one client-side encoding cannot serve
	// both. The server picks the probed clusters itself (the nprobe centroids nearest
	// the query by inner product over its loaded set) and forces nprobe from instance
	// config, so the request carries only the query.
	Query []float32 `protobuf:"fixed32,1,rep,packed,name=query,proto3" json:"query,omitempty"`
	// Requester's allowed filter-tag scope (opaque). An item survives if it has no
	// tags (public) or ≥1 tag intersecting this scope; the rest are folded into each
	// cell's dead. Empty/unset = no filter (return all). Trusted from the caller (no
	// signature yet); scope provenance is the caller's (Console's) responsibility.
	FilterScope   []string `protobuf:"bytes,4,rep,name=filter_scope,json=filterScope,proto3" json:"filter_scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{17}
}

func (x *SearchRequest) GetQuery() []float32 {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SearchRequest) GetFilterScope() []string {
	if x != nil {
		return x.FilterScope
	}
	return nil
}

// CellResult is one cell's encrypted score blob, tagged with its cell id. Both
// tiers return it: the flat (RMP/IP0) cells and the cluster (MM/IP1) cells. The
// two tiers use different CKKS contexts, so the client decrypts each tier's
// blobs with the matching key — but a result position is addressed the same way,
// (cell_id, row). cell_id is scoped per tier (an rmp cell id and an mm cell id
// are independent namespaces, disambiguated by which list the result is in).
type CellResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellId        uint32                 `protobuf:"varint,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	Blob          []byte                 `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
	Dead          []byte                 `protobuf:"bytes,4,opt,name=dead,proto3" json:"dead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellResult) Reset() {
	*x = CellResult{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellResult) ProtoMessage() {}

func (x *CellResult) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellResult.ProtoReflect.Descriptor instead.
func (*CellResult) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{18}
}

func (x *CellResult) GetCellId() uint32 {
	if x != nil {
		return x.CellId
	}
	return 0
}

func (x *CellResult) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *CellResult) GetDead() []byte {
	if x != nil {
		return x.Dead
	}
	return nil
}

type SearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Liveness epoch the dead data was captured at. Monotonic, so a racing delete
	// only ever over-excludes (dead is captured after the blobs), never leaks.
	TombEpoch int64 `protobuf:"varint,1,opt,name=tomb_epoch,json=tombEpoch,proto3" json:"tomb_epoch,omitempty"`
	// Flat (RMP) tier cells — one blob per live flat cell (active + sealed). The
	// client decrypts each with the RMP key, drops dead, and ranks across cells.
	Rmp []*CellResult `protobuf:"bytes,2,rep,name=rmp,proto3" json:"rmp,omitempty"`
	// Per probed cluster (MM) cell — empty when the cluster tier is unconfigured or
	// no cluster cell was probed.
	Mm            []*CellResult `protobuf:"bytes,3,rep,name=mm,proto3" json:"mm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{19}
}

func (x *SearchResponse) GetTombEpoch() int64 {
	if x != nil {
		return x.TombEpoch
	}
	return 0
}

func (x *SearchResponse) GetRmp() []*CellResult {
	if x != nil {
		return x.Rmp
	}
	return nil
}

func (x *SearchResponse) GetMm() []*CellResult {
	if x != nil {
		return x.Mm
	}
	return nil
}

// CellRow addresses one result position (cell id + cell-local row) for metadata
// resolution, in either tier. cell_id is scoped per tier (see GetMetadataRequest).
type CellRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellId        uint32                 `protobuf:"varint,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	Row           int64                  `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellRow) Reset() {
	*x = CellRow{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellRow) ProtoMessage() {}

func (x *CellRow) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellRow.ProtoReflect.Descriptor instead.
func (*CellRow) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{20}
}

func (x *CellRow) GetCellId() uint32 {
	if x != nil {
		return x.CellId
	}
	return 0
}

func (x *CellRow) GetRow() int64 {
	if x != nil {
		return x.Row
	}
	return 0
}

type GetMetadataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Flat (RMP) cell positions to resolve via the live flat cells' row->id maps.
	RmpRows []*CellRow `protobuf:"bytes,3,rep,name=rmp_rows,json=rmpRows,proto3" json:"rmp_rows,omitempty"`
	// Cluster (MM) cell positions to resolve via the live cluster cells' row->id maps.
	MmRows []*CellRow `protobuf:"bytes,2,rep,name=mm_rows,json=mmRows,proto3" json:"mm_rows,omitempty"`
	// Same scope as the paired Search. A resolved position whose id is out of scope is
	// returned with an empty id — the boundary's second gate, so a caller can't
	// re-resolve a dead position back to its id/tag membership. Empty/unset = no gate.
	FilterScope   []string `protobuf:"bytes,4,rep,name=filter_scope,json=filterScope,proto3" json:"filter_scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{21}
}

func (x *GetMetadataRequest) GetRmpRows() []*CellRow {
	if x != nil {
		return x.RmpRows
	}
	return nil
}

func (x *GetMetadataRequest) GetMmRows() []*CellRow {
	if x != nil {
		return x.MmRows
	}
	return nil
}

func (x *GetMetadataRequest) GetFilterScope() []string {
	if x != nil {
		return x.FilterScope
	}
	return nil
}

type GetMetadataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One entry per rmp_rows element, in the same order, so the client zips each
	// back to its score. An unknown position yields an entry with an empty id.
	RmpEntries []*MetadataEntry `protobuf:"bytes,1,rep,name=rmp_entries,json=rmpEntries,proto3" json:"rmp_entries,omitempty"`
	// One entry per mm_rows element, in the same order.
	MmEntries     []*MetadataEntry `protobuf:"bytes,2,rep,name=mm_entries,json=mmEntries,proto3" json:"mm_entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{22}
}

func (x *GetMetadataResponse) GetRmpEntries() []*MetadataEntry {
	if x != nil {
		return x.RmpEntries
	}
	return nil
}

func (x *GetMetadataResponse) GetMmEntries() []*MetadataEntry {
	if x != nil {
		return x.MmEntries
	}
	return nil
}

type MetadataEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // opaque UUID ("" if the slot has no manifest row)
	Metadata      string                 `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"` // stored JSON document (plaintext)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataEntry) Reset() {
	*x = MetadataEntry{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataEntry) ProtoMessage() {}

func (x *MetadataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataEntry.ProtoReflect.Descriptor instead.
func (*MetadataEntry) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{23}
}

func (x *MetadataEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetadataEntry) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // opaque UUID to tombstone
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{25}
}

// UpdateTagsRequest changes an item's opaque filter-tag set. add and remove are
// applied to the current set (add wins on overlap); both are idempotent. An unknown
// id is a no-op.
type UpdateTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Add           []string               `protobuf:"bytes,2,rep,name=add,proto3" json:"add,omitempty"`
	Remove        []string               `protobuf:"bytes,3,rep,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagsRequest) Reset() {
	*x = UpdateTagsRequest{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagsRequest) ProtoMessage() {}

func (x *UpdateTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagsRequest.ProtoReflect.Descriptor instead.
func (*UpdateTagsRequest) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateTagsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTagsRequest) GetAdd() []string {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *UpdateTagsRequest) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

type UpdateTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagsResponse) Reset() {
	*x = UpdateTagsResponse{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagsResponse) ProtoMessage() {}

func (x *UpdateTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagsResponse.ProtoReflect.Descriptor instead.
func (*UpdateTagsResponse) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{27}
}

// RetagAllRequest replaces one opaque filter tag with another across every item
// carrying it. from and to are required and must differ (an item already holding
// to keeps a single copy — set semantics). To strip a tag entirely use RemoveTag.
type RetagAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetagAllRequest) Reset() {
	*x = RetagAllRequest{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetagAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetagAllRequest) ProtoMessage() {}

func (x *RetagAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetagAllRequest.ProtoReflect.Descriptor instead.
func (*RetagAllRequest) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{28}
}

func (x *RetagAllRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *RetagAllRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

// RetagAllResponse reports how many items had their tag set changed.
type RetagAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       uint64                 `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetagAllResponse) Reset() {
	*x = RetagAllResponse{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetagAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetagAllResponse) ProtoMessage() {}

func (x *RetagAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetagAllResponse.ProtoReflect.Descriptor instead.
func (*RetagAllResponse) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{29}
}

func (x *RetagAllResponse) GetChanged() uint64 {
	if x != nil {
		return x.Changed
	}
	return 0
}

// RemoveTagRequest strips one opaque filter tag from every item carrying it. tag
// is required.
type RemoveTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTagRequest) Reset() {
	*x = RemoveTagRequest{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTagRequest) ProtoMessage() {}

func (x *RemoveTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTagRequest.ProtoReflect.Descriptor instead.
func (*RemoveTagRequest) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{30}
}

func (x *RemoveTagRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// RemoveTagResponse reports how many items had the tag removed.
type RemoveTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       uint64                 `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTagResponse) Reset() {
	*x = RemoveTagResponse{}
	mi := &file_runespace_v1_runespace_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTagResponse) ProtoMessage() {}

func (x *RemoveTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runespace_v1_runespace_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTagResponse.ProtoReflect.Descriptor instead.
func (*RemoveTagResponse) Descriptor() ([]byte, []int) {
	return file_runespace_v1_runespace_proto_rawDescGZIP(), []int{31}
}

func (x *RemoveTagResponse) GetChanged() uint64 {
	if x != nil {
		return x.Changed
	}
	return 0
}

var File_runespace_v1_runespace_proto protoreflect.FileDescriptor

const file_runespace_v1_runespace_proto_rawDesc = "" +
	"\n" +
	"\x1crunespace/v1/runespace.proto\x12\frunespace.v1\"\x10\n" +
	"\x0eGetInfoRequest\"\xb7\x02\n" +
	"\x0fGetInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12\x1d\n" +
	"\n" +
	"build_date\x18\x03 \x01(\tR\tbuildDate\x12#\n" +
	"\rengine_status\x18\x04 \x01(\tR\fengineStatus\x12(\n" +
	"\x10engine_probe_dim\x18\x05 \x01(\rR\x0eengineProbeDim\x12\x14\n" +
	"\x05ready\x18\x06 \x01(\bR\x05ready\x12>\n" +
	"\x0fregistered_keys\x18\a \x03(\v2\x15.runespace.v1.KeyMetaR\x0eregisteredKeys\x12.\n" +
	"\x05stats\x18\b \x01(\v2\x18.runespace.v1.SpaceStatsR\x05stats\"[\n" +
	"\n" +
	"SpaceStats\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\x04R\x04rows\x12\x19\n" +
	"\bmax_rows\x18\x02 \x01(\x04R\amaxRows\x12\x1e\n" +
	"\n" +
	"tombstoned\x18\x03 \x01(\x04R\n" +
	"tombstoned\"\x1c\n" +
	"\x1aRegisterKeysStreamResponse\"\xa2\x01\n" +
	"\x19RegisterKeysStreamRequest\x121\n" +
	"\x06header\x18\x01 \x01(\v2\x17.runespace.v1.KeyHeaderH\x00R\x06header\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x121\n" +
	"\x06footer\x18\x03 \x01(\v2\x17.runespace.v1.KeyFooterH\x00R\x06footerB\t\n" +
	"\apayload\"\xac\x01\n" +
	"\tKeyHeader\x12)\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x15.runespace.v1.KeyKindR\x04kind\x12\x1b\n" +
	"\ttotal_len\x18\x02 \x01(\x04R\btotalLen\x12\x10\n" +
	"\x03kid\x18\x03 \x01(\tR\x03kid\x12\x16\n" +
	"\x06preset\x18\x04 \x01(\tR\x06preset\x12\x10\n" +
	"\x03dim\x18\x05 \x01(\rR\x03dim\x12\x1b\n" +
	"\teval_mode\x18\x06 \x01(\tR\bevalMode\"#\n" +
	"\tKeyFooter\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\fR\x06sha256\"\xaf\x01\n" +
	"\aKeyMeta\x12)\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x15.runespace.v1.KeyKindR\x04kind\x12\x10\n" +
	"\x03kid\x18\x02 \x01(\tR\x03kid\x12\x16\n" +
	"\x06preset\x18\x03 \x01(\tR\x06preset\x12\x10\n" +
	"\x03dim\x18\x04 \x01(\rR\x03dim\x12\x1b\n" +
	"\teval_mode\x18\x05 \x01(\tR\bevalMode\x12 \n" +
	"\vfingerprint\x18\x06 \x01(\fR\vfingerprint\"\xbd\x01\n" +
	"\rInsertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\tR\bmetadata\x120\n" +
	"\brmp_item\x18\x03 \x01(\v2\x15.runespace.v1.RMPItemR\armpItem\x12-\n" +
	"\amm_item\x18\x04 \x01(\v2\x14.runespace.v1.MMItemR\x06mmItem\x12\x1f\n" +
	"\vfilter_tags\x18\x05 \x03(\tR\n" +
	"filterTags\"\x1d\n" +
	"\aRMPItem\x12\x12\n" +
	"\x04item\x18\x01 \x01(\fR\x04item\"m\n" +
	"\x06MMItem\x12\x12\n" +
	"\x04item\x18\x01 \x01(\fR\x04item\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\rR\tclusterId\x120\n" +
	"\x14centroid_set_version\x18\x03 \x01(\tR\x12centroidSetVersion\"\x10\n" +
	"\x0eInsertResponse\"\x15\n" +
	"\x13GetCentroidsRequest\",\n" +
	"\bCentroid\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03vec\x18\x02 \x03(\x02R\x03vec\"\x8e\x01\n" +
	"\x11GetCentroidsChunk\x129\n" +
	"\x06header\x18\x01 \x01(\v2\x1f.runespace.v1.CentroidSetHeaderH\x00R\x06header\x123\n" +
	"\x05batch\x18\x02 \x01(\v2\x1b.runespace.v1.CentroidBatchH\x00R\x05batchB\t\n" +
	"\apayload\"m\n" +
	"\x11CentroidSetHeader\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x10\n" +
	"\x03dim\x18\x02 \x01(\rR\x03dim\x12\x16\n" +
	"\x06preset\x18\x03 \x01(\tR\x06preset\x12\x14\n" +
	"\x05nlist\x18\x04 \x01(\rR\x05nlist\"E\n" +
	"\rCentroidBatch\x124\n" +
	"\tcentroids\x18\x01 \x03(\v2\x16.runespace.v1.CentroidR\tcentroids\"z\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x03(\x02R\x05query\x12!\n" +
	"\ffilter_scope\x18\x04 \x03(\tR\vfilterScopeJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04R\x0eprobe_clustersR\x14centroid_set_version\"S\n" +
	"\n" +
	"CellResult\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\rR\x06cellId\x12\x12\n" +
	"\x04blob\x18\x02 \x01(\fR\x04blob\x12\x12\n" +
	"\x04dead\x18\x04 \x01(\fR\x04deadJ\x04\b\x03\x10\x04\"\x85\x01\n" +
	"\x0eSearchResponse\x12\x1d\n" +
	"\n" +
	"tomb_epoch\x18\x01 \x01(\x03R\ttombEpoch\x12*\n" +
	"\x03rmp\x18\x02 \x03(\v2\x18.runespace.v1.CellResultR\x03rmp\x12(\n" +
	"\x02mm\x18\x03 \x03(\v2\x18.runespace.v1.CellResultR\x02mm\"4\n" +
	"\aCellRow\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\rR\x06cellId\x12\x10\n" +
	"\x03row\x18\x02 \x01(\x03R\x03row\"\xaa\x01\n" +
	"\x12GetMetadataRequest\x120\n" +
	"\brmp_rows\x18\x03 \x03(\v2\x15.runespace.v1.CellRowR\armpRows\x12.\n" +
	"\amm_rows\x18\x02 \x03(\v2\x15.runespace.v1.CellRowR\x06mmRows\x12!\n" +
	"\ffilter_scope\x18\x04 \x03(\tR\vfilterScopeJ\x04\b\x01\x10\x02R\trmp_slots\"\x8f\x01\n" +
	"\x13GetMetadataResponse\x12<\n" +
	"\vrmp_entries\x18\x01 \x03(\v2\x1b.runespace.v1.MetadataEntryR\n" +
	"rmpEntries\x12:\n" +
	"\n" +
	"mm_entries\x18\x02 \x03(\v2\x1b.runespace.v1.MetadataEntryR\tmmEntries\";\n" +
	"\rMetadataEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\tR\bmetadata\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x10\n" +
	"\x0eDeleteResponse\"M\n" +
	"\x11UpdateTagsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03add\x18\x02 \x03(\tR\x03add\x12\x16\n" +
	"\x06remove\x18\x03 \x03(\tR\x06remove\"\x14\n" +
	"\x12UpdateTagsResponse\"5\n" +
	"\x0fRetagAllRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\",\n" +
	"\x10RetagAllResponse\x12\x18\n" +
	"\achanged\x18\x01 \x01(\x04R\achanged\"$\n" +
	"\x10RemoveTagRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\"-\n" +
	"\x11RemoveTagResponse\x12\x18\n" +
	"\achanged\x18\x01 \x01(\x04R\achanged*P\n" +
	"\aKeyKind\x12\x18\n" +
	"\x14KEY_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11KEY_KIND_RMP_EVAL\x10\x01\x12\x14\n" +
	"\x10KEY_KIND_MM_EVAL\x10\x022\xa8\x06\n" +
	"\x10RuneSpaceService\x12F\n" +
	"\aGetInfo\x12\x1c.runespace.v1.GetInfoRequest\x1a\x1d.runespace.v1.GetInfoResponse\x12i\n" +
	"\x12RegisterKeysStream\x12'.runespace.v1.RegisterKeysStreamRequest\x1a(.runespace.v1.RegisterKeysStreamResponse(\x01\x12C\n" +
	"\x06Insert\x12\x1b.runespace.v1.InsertRequest\x1a\x1c.runespace.v1.InsertResponse\x12C\n" +
	"\x06Search\x12\x1b.runespace.v1.SearchRequest\x1a\x1c.runespace.v1.SearchResponse\x12T\n" +
	"\fGetCentroids\x12!.runespace.v1.GetCentroidsRequest\x1a\x1f.runespace.v1.GetCentroidsChunk0\x01\x12R\n" +
	"\vGetMetadata\x12 .runespace.v1.GetMetadataRequest\x1a!.runespace.v1.GetMetadataResponse\x12C\n" +
	"\x06Delete\x12\x1b.runespace.v1.DeleteRequest\x1a\x1c.runespace.v1.DeleteResponse\x12O\n" +
	"\n" +
	"UpdateTags\x12\x1f.runespace.v1.UpdateTagsRequest\x1a .runespace.v1.UpdateTagsResponse\x12I\n" +
	"\bRetagAll\x12\x1d.runespace.v1.RetagAllRequest\x1a\x1e.runespace.v1.RetagAllResponse\x12L\n" +
	"\tRemoveTag\x12\x1e.runespace.v1.RemoveTagRequest\x1a\x1f.runespace.v1.RemoveTagResponseBCZAgithub.com/jh-lee-cryptolab/runespace/pkg/runespacepb;runespacepbb\x06proto3"

var (
	file_runespace_v1_runespace_proto_rawDescOnce sync.Once
	file_runespace_v1_runespace_proto_rawDescData []byte
)

func file_runespace_v1_runespace_proto_rawDescGZIP() []byte {
	file_runespace_v1_runespace_proto_rawDescOnce.Do(func() {
		file_runespace_v1_runespace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runespace_v1_runespace_proto_rawDesc), len(file_runespace_v1_runespace_proto_rawDesc)))
	})
	return file_runespace_v1_runespace_proto_rawDescData
}

var file_runespace_v1_runespace_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_runespace_v1_runespace_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_runespace_v1_runespace_proto_goTypes = []any{
	(KeyKind)(0),                       // 0: runespace.v1.KeyKind
	(*GetInfoRequest)(nil),             // 1: runespace.v1.GetInfoRequest
	(*GetInfoResponse)(nil),            // 2: runespace.v1.GetInfoResponse
	(*SpaceStats)(nil),                 // 3: runespace.v1.SpaceStats
	(*RegisterKeysStreamResponse)(nil), // 4: runespace.v1.RegisterKeysStreamResponse
	(*RegisterKeysStreamRequest)(nil),  // 5: runespace.v1.RegisterKeysStreamRequest
	(*KeyHeader)(nil),                  // 6: runespace.v1.KeyHeader
	(*KeyFooter)(nil),                  // 7: runespace.v1.KeyFooter
	(*KeyMeta)(nil),                    // 8: runespace.v1.KeyMeta
	(*InsertRequest)(nil),              // 9: runespace.v1.InsertRequest
	(*RMPItem)(nil),                    // 10: runespace.v1.RMPItem
	(*MMItem)(nil),                     // 11: runespace.v1.MMItem
	(*InsertResponse)(nil),             // 12: runespace.v1.InsertResponse
	(*GetCentroidsRequest)(nil),        // 13: runespace.v1.GetCentroidsRequest
	(*Centroid)(nil),                   // 14: runespace.v1.Centroid
	(*GetCentroidsChunk)(nil),          // 15: runespace.v1.GetCentroidsChunk
	(*CentroidSetHeader)(nil),          // 16: runespace.v1.CentroidSetHeader
	(*CentroidBatch)(nil),              // 17: runespace.v1.CentroidBatch
	(*SearchRequest)(nil),              // 18: runespace.v1.SearchRequest
	(*CellResult)(nil),                 // 19: runespace.v1.CellResult
	(*SearchResponse)(nil),             // 20: runespace.v1.SearchResponse
	(*CellRow)(nil),                    // 21: runespace.v1.CellRow
	(*GetMetadataRequest)(nil),         // 22: runespace.v1.GetMetadataRequest
	(*GetMetadataResponse)(nil),        // 23: runespace.v1.GetMetadataResponse
	(*MetadataEntry)(nil),              // 24: runespace.v1.MetadataEntry
	(*DeleteRequest)(nil),              // 25: runespace.v1.DeleteRequest
	(*DeleteResponse)(nil),             // 26: runespace.v1.DeleteResponse
	(*UpdateTagsRequest)(nil),          // 27: runespace.v1.UpdateTagsRequest
	(*UpdateTagsResponse)(nil),         // 28: runespace.v1.UpdateTagsResponse
	(*RetagAllRequest)(nil),            // 29: runespace.v1.RetagAllRequest
	(*RetagAllResponse)(nil),           // 30: runespace.v1.RetagAllResponse
	(*RemoveTagRequest)(nil),           // 31: runespace.v1.RemoveTagRequest
	(*RemoveTagResponse)(nil),          // 32: runespace.v1.RemoveTagResponse
}
var file_runespace_v1_runespace_proto_depIdxs = []int32{
	8,  // 0: runespace.v1.GetInfoResponse.registered_keys:type_name -> runespace.v1.KeyMeta
	3,  // 1: runespace.v1.GetInfoResponse.stats:type_name -> runespace.v1.SpaceStats
	6,  // 2: runespace.v1.RegisterKeysStreamRequest.header:type_name -> runespace.v1.KeyHeader
	7,  // 3: runespace.v1.RegisterKeysStreamRequest.footer:type_name -> runespace.v1.KeyFooter
	0,  // 4: runespace.v1.KeyHeader.kind:type_name -> runespace.v1.KeyKind
	0,  // 5: runespace.v1.KeyMeta.kind:type_name -> runespace.v1.KeyKind
	10, // 6: runespace.v1.InsertRequest.rmp_item:type_name -> runespace.v1.RMPItem
	11, // 7: runespace.v1.InsertRequest.mm_item:type_name -> runespace.v1.MMItem
	16, // 8: runespace.v1.GetCentroidsChunk.header:type_name -> runespace.v1.CentroidSetHeader
	17, // 9: runespace.v1.GetCentroidsChunk.batch:type_name -> runespace.v1.CentroidBatch
	14, // 10: runespace.v1.CentroidBatch.centroids:type_name -> runespace.v1.Centroid
	19, // 11: runespace.v1.SearchResponse.rmp:type_name -> runespace.v1.CellResult
	19, // 12: runespace.v1.SearchResponse.mm:type_name -> runespace.v1.CellResult
	21, // 13: runespace.v1.GetMetadataRequest.rmp_rows:type_name -> runespace.v1.CellRow
	21, // 14: runespace.v1.GetMetadataRequest.mm_rows:type_name -> runespace.v1.CellRow
	24, // 15: runespace.v1.GetMetadataResponse.rmp_entries:type_name -> runespace.v1.MetadataEntry
	24, // 16: runespace.v1.GetMetadataResponse.mm_entries:type_name -> runespace.v1.MetadataEntry
	1,  // 17: runespace.v1.RuneSpaceService.GetInfo:input_type -> runespace.v1.GetInfoRequest
	5,  // 18: runespace.v1.RuneSpaceService.RegisterKeysStream:input_type -> runespace.v1.RegisterKeysStreamRequest
	9,  // 19: runespace.v1.RuneSpaceService.Insert:input_type -> runespace.v1.InsertRequest
	18, // 20: runespace.v1.RuneSpaceService.Search:input_type -> runespace.v1.SearchRequest
	13, // 21: runespace.v1.RuneSpaceService.GetCentroids:input_type -> runespace.v1.GetCentroidsRequest
	22, // 22: runespace.v1.RuneSpaceService.GetMetadata:input_type -> runespace.v1.GetMetadataRequest
	25, // 23: runespace.v1.RuneSpaceService.Delete:input_type -> runespace.v1.DeleteRequest
	27, // 24: runespace.v1.RuneSpaceService.UpdateTags:input_type -> runespace.v1.UpdateTagsRequest
	29, // 25: runespace.v1.RuneSpaceService.RetagAll:input_type -> runespace.v1.RetagAllRequest
	31, // 26: runespace.v1.RuneSpaceService.RemoveTag:input_type -> runespace.v1.RemoveTagRequest
	2,  // 27: runespace.v1.RuneSpaceService.GetInfo:output_type -> runespace.v1.GetInfoResponse
	4,  // 28: runespace.v1.RuneSpaceService.RegisterKeysStream:output_type -> runespace.v1.RegisterKeysStreamResponse
	12, // 29: runespace.v1.RuneSpaceService.Insert:output_type -> runespace.v1.InsertResponse
	20, // 30: runespace.v1.RuneSpaceService.Search:output_type -> runespace.v1.SearchResponse
	15, // 31: runespace.v1.RuneSpaceService.GetCentroids:output_type -> runespace.v1.GetCentroidsChunk
	23, // 32: runespace.v1.RuneSpaceService.GetMetadata:output_type -> runespace.v1.GetMetadataResponse
	26, // 33: runespace.v1.RuneSpaceService.Delete:output_type -> runespace.v1.DeleteResponse
	28, // 34: runespace.v1.RuneSpaceService.UpdateTags:output_type -> runespace.v1.UpdateTagsResponse
	30, // 35: runespace.v1.RuneSpaceService.RetagAll:output_type -> runespace.v1.RetagAllResponse
	32, // 36: runespace.v1.RuneSpaceService.RemoveTag:output_type -> runespace.v1.RemoveTagResponse
	27, // [27:37] is the sub-list for method output_type
	17, // [17:27] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_runespace_v1_runespace_proto_init() }
func file_runespace_v1_runespace_proto_init() {
	if File_runespace_v1_runespace_proto != nil {
		return
	}
	file_runespace_v1_runespace_proto_msgTypes[4].OneofWrappers = []any{
		(*RegisterKeysStreamRequest_Header)(nil),
		(*RegisterKeysStreamRequest_Data)(nil),
		(*RegisterKeysStreamRequest_Footer)(nil),
	}
	file_runespace_v1_runespace_proto_msgTypes[14].OneofWrappers = []any{
		(*GetCentroidsChunk_Header)(nil),
		(*GetCentroidsChunk_Batch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runespace_v1_runespace_proto_rawDesc), len(file_runespace_v1_runespace_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runespace_v1_runespace_proto_goTypes,
		DependencyIndexes: file_runespace_v1_runespace_proto_depIdxs,
		EnumInfos:         file_runespace_v1_runespace_proto_enumTypes,
		MessageInfos:      file_runespace_v1_runespace_proto_msgTypes,
	}.Build()
	File_runespace_v1_runespace_proto = out.File
	file_runespace_v1_runespace_proto_goTypes = nil
	file_runespace_v1_runespace_proto_depIdxs = nil
}
