// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: runespace/v1/runespace.proto

package runespacepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuneSpaceService_GetInfo_FullMethodName            = "/runespace.v1.RuneSpaceService/GetInfo"
	RuneSpaceService_RegisterKeysStream_FullMethodName = "/runespace.v1.RuneSpaceService/RegisterKeysStream"
	RuneSpaceService_Insert_FullMethodName             = "/runespace.v1.RuneSpaceService/Insert"
	RuneSpaceService_Search_FullMethodName             = "/runespace.v1.RuneSpaceService/Search"
	RuneSpaceService_GetCentroids_FullMethodName       = "/runespace.v1.RuneSpaceService/GetCentroids"
	RuneSpaceService_GetMetadata_FullMethodName        = "/runespace.v1.RuneSpaceService/GetMetadata"
	RuneSpaceService_Delete_FullMethodName             = "/runespace.v1.RuneSpaceService/Delete"
	RuneSpaceService_UpdateTags_FullMethodName         = "/runespace.v1.RuneSpaceService/UpdateTags"
	RuneSpaceService_RetagAll_FullMethodName           = "/runespace.v1.RuneSpaceService/RetagAll"
	RuneSpaceService_RemoveTag_FullMethodName          = "/runespace.v1.RuneSpaceService/RemoveTag"
)

// RuneSpaceServiceClient is the client API for RuneSpaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RuneSpaceService is the per-team data-plane API for the encrypted vector index
// engine. The engine holds only the PUBLIC evaluation key (never the secret
// key); decryption happens client-side / in Vault.
//
// Provisioning: the instance boots UNREGISTERED. RegisterKeysStream loads the
// RMP+MM eval keys (persisted to the PV, reloaded on restart/crash). Insert,
// Search, and Delete are rejected with FAILED_PRECONDITION until keys are
// registered.
type RuneSpaceServiceClient interface {
	// GetInfo returns build metadata, a live cgo self-check of the evi engine,
	// whether eval keys are registered (ready), and the space occupancy counts.
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	// RegisterKeysStream loads the PUBLIC RMP+MM evaluation keys into the engine
	// and persists them to the PV. Eval keys exceed the per-message size limit
	// (the MM eval key is hundreds of MB), so the client streams each key as a
	// header, its data chunks in order, then a footer carrying a sha256 the server
	// verifies before applying. One-shot (rotation is future); required before any
	// data-plane RPC.
	RegisterKeysStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RegisterKeysStreamRequest, RegisterKeysStreamResponse], error)
	// Insert appends one encrypted item under a client-supplied opaque id. The
	// item carries a flat (RMP) representation and, when the cluster tier is
	// configured, a compact cluster (MM) representation plus its routed
	// cluster id. Idempotent: re-inserting an existing id is a no-op.
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	// Search runs a blind homomorphic search and returns the serialized encrypted
	// result blob; the client decrypts and ranks.
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// GetCentroids streams the immutable IVF centroid set the instance loaded at
	// boot: one header frame (version/dim/preset/nlist), then the centroids in
	// id-ordered batches. A client reads it once and caches it to compute, in
	// plaintext, the nearest cluster for an Insert. It is streamed rather than
	// returned whole because a large set (nlist*dim floats) can exceed the
	// per-message size limit. The set is version-pinned by a content hash; clients
	// echo that as centroid_set_version on Insert. An empty version in the header
	// means the cluster tier is not configured on this instance, which cannot
	// accept inserts (every insert requires an mm_item routed against a centroid
	// set).
	GetCentroids(ctx context.Context, in *GetCentroidsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetCentroidsChunk], error)
	// GetMetadata resolves search-result cell positions (cell_id, row) to
	// (id, metadata) in one round-trip (the manifest-fetch step).
	GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error)
	// Delete soft-deletes an id (plaintext tombstone filtered at query time —
	// NOT an FHE masking op).
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// UpdateTags changes an item's opaque filter-tag set (add/remove) — the
	// visibility labels Search intersects with a request scope. Memory-first then
	// durable so a removed tag stops matching immediately.
	UpdateTags(ctx context.Context, in *UpdateTagsRequest, opts ...grpc.CallOption) (*UpdateTagsResponse, error)
	// RetagAll replaces filter tag `from` with `to` on every item that currently
	// carries `from`, applied per item (memory-first then durable) like UpdateTags
	// — no cell mutation or rebalance. Idempotent and re-runnable: an item already
	// carrying `to` keeps a single copy. `from` and `to` are required and must
	// differ; use RemoveTag to strip a tag entirely.
	RetagAll(ctx context.Context, in *RetagAllRequest, opts ...grpc.CallOption) (*RetagAllResponse, error)
	// RemoveTag strips filter tag `tag` from every item that currently carries it,
	// applied per item (memory-first then durable) like UpdateTags. Idempotent and
	// re-runnable.
	RemoveTag(ctx context.Context, in *RemoveTagRequest, opts ...grpc.CallOption) (*RemoveTagResponse, error)
}

type runeSpaceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuneSpaceServiceClient(cc grpc.ClientConnInterface) RuneSpaceServiceClient {
	return &runeSpaceServiceClient{cc}
}

func (c *runeSpaceServiceClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, RuneSpaceService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runeSpaceServiceClient) RegisterKeysStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RegisterKeysStreamRequest, RegisterKeysStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuneSpaceService_ServiceDesc.Streams[0], RuneSpaceService_RegisterKeysStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RegisterKeysStreamRequest, RegisterKeysStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuneSpaceService_RegisterKeysStreamClient = grpc.ClientStreamingClient[RegisterKeysStreamRequest, RegisterKeysStreamResponse]

func (c *runeSpaceServiceClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, RuneSpaceService_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runeSpaceServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, RuneSpaceService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runeSpaceServiceClient) GetCentroids(ctx context.Context, in *GetCentroidsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetCentroidsChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuneSpaceService_ServiceDesc.Streams[1], RuneSpaceService_GetCentroids_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetCentroidsRequest, GetCentroidsChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuneSpaceService_GetCentroidsClient = grpc.ServerStreamingClient[GetCentroidsChunk]

func (c *runeSpaceServiceClient) GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetadataResponse)
	err := c.cc.Invoke(ctx, RuneSpaceService_GetMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runeSpaceServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, RuneSpaceService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runeSpaceServiceClient) UpdateTags(ctx context.Context, in *UpdateTagsRequest, opts ...grpc.CallOption) (*UpdateTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTagsResponse)
	err := c.cc.Invoke(ctx, RuneSpaceService_UpdateTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runeSpaceServiceClient) RetagAll(ctx context.Context, in *RetagAllRequest, opts ...grpc.CallOption) (*RetagAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetagAllResponse)
	err := c.cc.Invoke(ctx, RuneSpaceService_RetagAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runeSpaceServiceClient) RemoveTag(ctx context.Context, in *RemoveTagRequest, opts ...grpc.CallOption) (*RemoveTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTagResponse)
	err := c.cc.Invoke(ctx, RuneSpaceService_RemoveTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuneSpaceServiceServer is the server API for RuneSpaceService service.
// All implementations must embed UnimplementedRuneSpaceServiceServer
// for forward compatibility.
//
// RuneSpaceService is the per-team data-plane API for the encrypted vector index
// engine. The engine holds only the PUBLIC evaluation key (never the secret
// key); decryption happens client-side / in Vault.
//
// Provisioning: the instance boots UNREGISTERED. RegisterKeysStream loads the
// RMP+MM eval keys (persisted to the PV, reloaded on restart/crash). Insert,
// Search, and Delete are rejected with FAILED_PRECONDITION until keys are
// registered.
type RuneSpaceServiceServer interface {
	// GetInfo returns build metadata, a live cgo self-check of the evi engine,
	// whether eval keys are registered (ready), and the space occupancy counts.
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	// RegisterKeysStream loads the PUBLIC RMP+MM evaluation keys into the engine
	// and persists them to the PV. Eval keys exceed the per-message size limit
	// (the MM eval key is hundreds of MB), so the client streams each key as a
	// header, its data chunks in order, then a footer carrying a sha256 the server
	// verifies before applying. One-shot (rotation is future); required before any
	// data-plane RPC.
	RegisterKeysStream(grpc.ClientStreamingServer[RegisterKeysStreamRequest, RegisterKeysStreamResponse]) error
	// Insert appends one encrypted item under a client-supplied opaque id. The
	// item carries a flat (RMP) representation and, when the cluster tier is
	// configured, a compact cluster (MM) representation plus its routed
	// cluster id. Idempotent: re-inserting an existing id is a no-op.
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)
	// Search runs a blind homomorphic search and returns the serialized encrypted
	// result blob; the client decrypts and ranks.
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// GetCentroids streams the immutable IVF centroid set the instance loaded at
	// boot: one header frame (version/dim/preset/nlist), then the centroids in
	// id-ordered batches. A client reads it once and caches it to compute, in
	// plaintext, the nearest cluster for an Insert. It is streamed rather than
	// returned whole because a large set (nlist*dim floats) can exceed the
	// per-message size limit. The set is version-pinned by a content hash; clients
	// echo that as centroid_set_version on Insert. An empty version in the header
	// means the cluster tier is not configured on this instance, which cannot
	// accept inserts (every insert requires an mm_item routed against a centroid
	// set).
	GetCentroids(*GetCentroidsRequest, grpc.ServerStreamingServer[GetCentroidsChunk]) error
	// GetMetadata resolves search-result cell positions (cell_id, row) to
	// (id, metadata) in one round-trip (the manifest-fetch step).
	GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error)
	// Delete soft-deletes an id (plaintext tombstone filtered at query time —
	// NOT an FHE masking op).
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// UpdateTags changes an item's opaque filter-tag set (add/remove) — the
	// visibility labels Search intersects with a request scope. Memory-first then
	// durable so a removed tag stops matching immediately.
	UpdateTags(context.Context, *UpdateTagsRequest) (*UpdateTagsResponse, error)
	// RetagAll replaces filter tag `from` with `to` on every item that currently
	// carries `from`, applied per item (memory-first then durable) like UpdateTags
	// — no cell mutation or rebalance. Idempotent and re-runnable: an item already
	// carrying `to` keeps a single copy. `from` and `to` are required and must
	// differ; use RemoveTag to strip a tag entirely.
	RetagAll(context.Context, *RetagAllRequest) (*RetagAllResponse, error)
	// RemoveTag strips filter tag `tag` from every item that currently carries it,
	// applied per item (memory-first then durable) like UpdateTags. Idempotent and
	// re-runnable.
	RemoveTag(context.Context, *RemoveTagRequest) (*RemoveTagResponse, error)
	mustEmbedUnimplementedRuneSpaceServiceServer()
}

// UnimplementedRuneSpaceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuneSpaceServiceServer struct{}

func (UnimplementedRuneSpaceServiceServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedRuneSpaceServiceServer) RegisterKeysStream(grpc.ClientStreamingServer[RegisterKeysStreamRequest, RegisterKeysStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method RegisterKeysStream not implemented")
}
func (UnimplementedRuneSpaceServiceServer) Insert(context.Context, *InsertRequest) (*InsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedRuneSpaceServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedRuneSpaceServiceServer) GetCentroids(*GetCentroidsRequest, grpc.ServerStreamingServer[GetCentroidsChunk]) error {
	return status.Error(codes.Unimplemented, "method GetCentroids not implemented")
}
func (UnimplementedRuneSpaceServiceServer) GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedRuneSpaceServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedRuneSpaceServiceServer) UpdateTags(context.Context, *UpdateTagsRequest) (*UpdateTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTags not implemented")
}
func (UnimplementedRuneSpaceServiceServer) RetagAll(context.Context, *RetagAllRequest) (*RetagAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetagAll not implemented")
}
func (UnimplementedRuneSpaceServiceServer) RemoveTag(context.Context, *RemoveTagRequest) (*RemoveTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTag not implemented")
}
func (UnimplementedRuneSpaceServiceServer) mustEmbedUnimplementedRuneSpaceServiceServer() {}
func (UnimplementedRuneSpaceServiceServer) testEmbeddedByValue()                          {}

// UnsafeRuneSpaceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuneSpaceServiceServer will
// result in compilation errors.
type UnsafeRuneSpaceServiceServer interface {
	mustEmbedUnimplementedRuneSpaceServiceServer()
}

func RegisterRuneSpaceServiceServer(s grpc.ServiceRegistrar, srv RuneSpaceServiceServer) {
	// If the following call panics, it indicates UnimplementedRuneSpaceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuneSpaceService_ServiceDesc, srv)
}

func _RuneSpaceService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuneSpaceServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuneSpaceService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuneSpaceServiceServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuneSpaceService_RegisterKeysStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RuneSpaceServiceServer).RegisterKeysStream(&grpc.GenericServerStream[RegisterKeysStreamRequest, RegisterKeysStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuneSpaceService_RegisterKeysStreamServer = grpc.ClientStreamingServer[RegisterKeysStreamRequest, RegisterKeysStreamResponse]

func _RuneSpaceService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuneSpaceServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuneSpaceService_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuneSpaceServiceServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuneSpaceService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuneSpaceServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuneSpaceService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuneSpaceServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuneSpaceService_GetCentroids_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetCentroidsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuneSpaceServiceServer).GetCentroids(m, &grpc.GenericServerStream[GetCentroidsRequest, GetCentroidsChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuneSpaceService_GetCentroidsServer = grpc.ServerStreamingServer[GetCentroidsChunk]

func _RuneSpaceService_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuneSpaceServiceServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuneSpaceService_GetMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuneSpaceServiceServer).GetMetadata(ctx, req.(*GetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuneSpaceService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuneSpaceServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuneSpaceService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuneSpaceServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuneSpaceService_UpdateTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuneSpaceServiceServer).UpdateTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuneSpaceService_UpdateTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuneSpaceServiceServer).UpdateTags(ctx, req.(*UpdateTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuneSpaceService_RetagAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetagAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuneSpaceServiceServer).RetagAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuneSpaceService_RetagAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuneSpaceServiceServer).RetagAll(ctx, req.(*RetagAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuneSpaceService_RemoveTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuneSpaceServiceServer).RemoveTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuneSpaceService_RemoveTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuneSpaceServiceServer).RemoveTag(ctx, req.(*RemoveTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuneSpaceService_ServiceDesc is the grpc.ServiceDesc for RuneSpaceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuneSpaceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runespace.v1.RuneSpaceService",
	HandlerType: (*RuneSpaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _RuneSpaceService_GetInfo_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _RuneSpaceService_Insert_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _RuneSpaceService_Search_Handler,
		},
		{
			MethodName: "GetMetadata",
			Handler:    _RuneSpaceService_GetMetadata_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RuneSpaceService_Delete_Handler,
		},
		{
			MethodName: "UpdateTags",
			Handler:    _RuneSpaceService_UpdateTags_Handler,
		},
		{
			MethodName: "RetagAll",
			Handler:    _RuneSpaceService_RetagAll_Handler,
		},
		{
			MethodName: "RemoveTag",
			Handler:    _RuneSpaceService_RemoveTag_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterKeysStream",
			Handler:       _RuneSpaceService_RegisterKeysStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetCentroids",
			Handler:       _RuneSpaceService_GetCentroids_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "runespace/v1/runespace.proto",
}
